### ISSUE TITLE
Admin bypass

### ISSUE THREAD

**Issue by JeffHD** [MineGaming/cubit#3]
Gibt es eine Möglichkeit, als Admin auf fremden Grundstücken auf die Kisten zuzugreifen. Aktuell schaffe ich es nur mit OP aber ich will nicht allen Mods und co. OP geben. Über die cubit.admin Permissions geht es nicht

**Comment by LinzN** [comment]
Hey, 
da die Protektion über worldguard läuft, muss man den bypass von Worldguard nehmen. Hier ein Auszug aus der Worldguard dokumentation. Hoffe du kannst damit was anfangen.

```
# Miscellaneous
worldguard.region.bypass.<world> (gives users with this permission the ability to bypass region protection)
worldguard.notify (Receive blacklist events notifications)
worldguard.chest-protection.override (override chest protection)
**worldguard.override.chest-protection** (alias for worldguard.chest-protection.override)
```

Gruß
Kekshaus

**Comment by JeffHD** [comment]
Danke dir hat funktioniert war aber **worldguard.region.bypass.<world>** was mein Problem dann gelöst hat.

Gruß

**Comment by LinzN** [comment]
Jop dass ist halt für einen ganzen Bypass. Das geht natürlich auch ^^.

Gruß
Kekshaus
